const PATH_ROOT = '/'
const PATH_LOGIN = `/logins`
const PATH_LOGIN_WAITING = `${PATH_LOGIN}/waiting`
const PATH_LOGIN_WAITING_GOOGLE = `${PATH_LOGIN_WAITING}/google`
const PATH_LOGIN_WAITING_FACEBOOK = `${PATH_LOGIN_WAITING}/facebook`
const PATH_LOGIN_WAITING_GITHUB = `${PATH_LOGIN_WAITING}/github`


export default {
  PATH_ROOT,
  PATH_LOGIN,
  PATH_LOGIN_WAITING,
  PATH_LOGIN_WAITING_GOOGLE,
  PATH_LOGIN_WAITING_FACEBOOK,
  PATH_LOGIN_WAITING_GITHUB,
}