import oc from 'open-color'

const WIDTH_CONTAINER_SIZE = '58rem'
const WIDTH_CONTENT_SIZE = '36rem'

const MEDIA_MOBILE = '768px'

const BASIC_FONT_COLOR = oc.gray[8]
const BASIC_BORDER_COLOR = oc.gray[4]
const BASIC_GRAY_BACKGROUND_COLOR = oc.gray[2]

const HEADER_Z_INDEX = 1000
const HEADER_HEIGHT = '4rem'

export default {
  MEDIA_MOBILE,

  BASIC_FONT_COLOR,
  BASIC_BORDER_COLOR,
  BASIC_GRAY_BACKGROUND_COLOR,

  HEADER_Z_INDEX,
  HEADER_HEIGHT,

  WIDTH_CONTAINER_SIZE,
  WIDTH_CONTENT_SIZE,
}
